<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click challenge environment</name>
   <tag></tag>
   <elementGuidId>c54c76ee-966e-42e5-a6ce-0d33ff6f61f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div[4]/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='__next']/div/div[2]/div/div[4]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d3e0a3b4-de30-4259-b285-b251a5eb9e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ReadyJoinChallanges_contEachNav__HAdBB</value>
      <webElementGuid>1c2b2068-5dfb-4bf0-b8b9-fc30a0c4d4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bae28bf3-ff2e-4da6-82ab-cd01a52b2750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;img alt=&quot;Icon Environtment&quot; srcSet=&quot;/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FIconEnvirontment.f370b429.png&amp;amp;w=32&amp;amp;q=75 1x, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2FIconEnvirontment.f370b429.png&amp;amp;w=48&amp;amp;q=75 2x&quot; src=&quot;/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FIconEnvirontment.f370b429.png&amp;amp;w=48&amp;amp;q=75&quot; decoding=&quot;async&quot; data-nimg=&quot;intrinsic&quot; style=&quot;position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;object-fit:contain&quot; loading=&quot;lazy&quot;/>Environment</value>
      <webElementGuid>41cb1e82-cc7e-48ab-8fd0-b460e5f31f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[4]/div[2]/div[2]</value>
      <webElementGuid>aee91a0a-69da-46c7-98a9-58783acb8285</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[4]/div[2]/div[2]</value>
      <webElementGuid>2fb808d8-73c2-4e64-a73a-f0843c9732ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ready to join the Challenge?'])[1]/following::div[6]</value>
      <webElementGuid>e946f5bf-f1a0-4be4-bf2f-2cec743f9265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaign #ForChange App Features'])[1]/following::div[33]</value>
      <webElementGuid>c7bb4b57-6341-4af3-b68d-99b5d3df2518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What They Say About Campaign #ForChange'])[1]/preceding::div[133]</value>
      <webElementGuid>79199052-40e2-4688-89db-0054dd09903d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lets Collaborate'])[2]/preceding::div[172]</value>
      <webElementGuid>73abfa66-2448-4e37-99be-82a5b93b740f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]</value>
      <webElementGuid>0c0ad949-9609-42ce-bd1d-73f9f33fb141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '&lt;img alt=&quot;Icon Environtment&quot; srcSet=&quot;/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FIconEnvirontment.f370b429.png&amp;amp;w=32&amp;amp;q=75 1x, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2FIconEnvirontment.f370b429.png&amp;amp;w=48&amp;amp;q=75 2x&quot; src=&quot;/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FIconEnvirontment.f370b429.png&amp;amp;w=48&amp;amp;q=75&quot; decoding=&quot;async&quot; data-nimg=&quot;intrinsic&quot; style=&quot;position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;object-fit:contain&quot; loading=&quot;lazy&quot;/>Environment' or . = '&lt;img alt=&quot;Icon Environtment&quot; srcSet=&quot;/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FIconEnvirontment.f370b429.png&amp;amp;w=32&amp;amp;q=75 1x, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2FIconEnvirontment.f370b429.png&amp;amp;w=48&amp;amp;q=75 2x&quot; src=&quot;/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FIconEnvirontment.f370b429.png&amp;amp;w=48&amp;amp;q=75&quot; decoding=&quot;async&quot; data-nimg=&quot;intrinsic&quot; style=&quot;position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;object-fit:contain&quot; loading=&quot;lazy&quot;/>Environment')]</value>
      <webElementGuid>59a1fc82-fa4b-439a-805e-62c3516eb91e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
