<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click challenge health</name>
   <tag></tag>
   <elementGuidId>2d2fb803-b34b-4b6e-98f4-f60279efb96f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div[4]/div[2]/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>92e4429b-28cc-48f3-9b96-05e558a427bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ReadyJoinChallanges_contEachNav__HAdBB</value>
      <webElementGuid>6b2b5195-952a-42ed-af77-36084ae4aee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2a2d1a55-ee11-48c0-b2f5-924974f9a222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Health</value>
      <webElementGuid>612bab6f-5dea-4c6d-b317-2c3566e6ef6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;GeneralLayout_contGeneral__FDHOU&quot;]/div[@class=&quot;GeneralLayout_childrenFlex__XWsLf&quot;]/div[1]/div[@class=&quot;ReadyJoinChallanges_contReadyJoinChallange__Lunm_&quot;]/div[@class=&quot;ReadyJoinChallanges_contNavGroupSlider__kISlg&quot;]/div[@class=&quot;ReadyJoinChallanges_contEachNav__HAdBB&quot;]</value>
      <webElementGuid>cfad1405-504c-49c1-ac02-16cde7d64b17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[4]/div[2]/div[4]</value>
      <webElementGuid>fde4b8cd-f612-474b-b443-24f8b37b49fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ready to join the Challenge?'])[1]/following::div[14]</value>
      <webElementGuid>8caca80a-40e2-4d42-a68c-f9d5bc86ce03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaign #ForChange App Features'])[1]/following::div[41]</value>
      <webElementGuid>06090477-5d5c-4ec6-84a9-645cf28353ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What They Say About Campaign #ForChange'])[1]/preceding::div[85]</value>
      <webElementGuid>5d447790-9f34-4f82-8b75-cafa36768c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lets Collaborate'])[2]/preceding::div[124]</value>
      <webElementGuid>0109cdab-e60a-431f-8f39-c0cef805e6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[4]</value>
      <webElementGuid>9f444eba-8bcc-4f8d-a4cc-7102a381b1e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Health' or . = 'Health')]</value>
      <webElementGuid>edef3917-3d71-43cd-b4b4-2819e8f7761a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
